/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageOfActivityResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                    sortBy?: string;
                    sortDir?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageOfJobApplicationResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateJobApplicationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobApplicationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobApplicationId: string;
            jobTitle: null | string;
            company: null | string;
            activityType: components["schemas"]["ActivityType"];
            /** Format: date-time */
            occurredAt: string;
            contactName: null | string;
            contactEmail: null | string;
            notes: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {unknown} */
        ActivityType: "Applied" | "PhoneScreen" | "Interview" | "Offer" | "Rejected" | "Withdrew" | "EmailedRecruiter" | "CalledRecruiter";
        PageOfActivityResponse: {
            items: components["schemas"]["ActivityResponse"][];
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            pageNumber: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        CreateJobApplicationRequest: {
            title: string;
            company: string;
            location: null | string;
            url: null | string;
            description: null | string;
            stage: components["schemas"]["Stage"];
            /** Format: date-time */
            appliedAt: null | string;
            /** Format: date-time */
            postedAt: null | string;
        };
        JobApplicationResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            company: string;
            location: null | string;
            url: null | string;
            description: null | string;
            stage: components["schemas"]["Stage"];
            /** Format: date-time */
            appliedAt: null | string;
            /** Format: date-time */
            postedAt: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PageOfJobApplicationResponse: {
            items: components["schemas"]["JobApplicationResponse"][];
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            pageNumber: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        /** @enum {unknown} */
        Stage: "Applied" | "Screening" | "Interviewing" | "Offer" | "Rejected" | "Withdrawn";
        UpdateJobApplicationRequest: {
            title: string;
            company: string;
            location: null | string;
            url: null | string;
            description: null | string;
            stage: components["schemas"]["Stage"];
            /** Format: date-time */
            appliedAt: null | string;
            /** Format: date-time */
            postedAt: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
